# Generated by Django 4.1.4 on 2023-02-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_order', models.DateTimeField(auto_created=True, verbose_name='Дата создания заказа')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('telephone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255)),
                ('link_messenger', models.CharField(blank=True, default='Ссылка отсутствует', max_length=255)),
                ('info_order', models.TextField(verbose_name='Информация о заказе')),
                ('car_brand', models.CharField(max_length=255, verbose_name='Марка авто')),
                ('car_model', models.CharField(max_length=255, verbose_name='Модель авто')),
                ('car_year', models.CharField(max_length=4, verbose_name='Год авто')),
                ('car_horsepower', models.CharField(max_length=255, verbose_name='Кол-во лошадиных сил')),
                ('car_vin', models.CharField(max_length=255, verbose_name='VIN-код')),
            ],
        ),
    ]
